name: learning anchors and custom actions
on: push
jobs:
  anchor-example:
    runs-on: ubuntu-latest
    # env: &my-env
    #   VAR_1: var1
    #   VAR_2: var2
    #   VAR_3: var3
    steps:
      - run: echo "anchor saved"
  using-custom-actions:
    runs-on: ubuntu-latest
    # env:
    #   <<: *my-env
    #   VAR_3: anothervar3
    steps:
      - uses: /samurodriguez/.github/actions/greeting@main
        with:
          name: Paco
      - uses: /samurodriguez/.github/actions/notify-slack@main
        id: notify-slack
        with:
          message: Holaaa
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          type: danger
      - run: echo ${{ steps.notify-slack.outputs.message-sent-at }}
  reusing-workflow:
    uses: /samurodriguez/.github/.github/workflows/setup-app.yml@main
