name: learning anchors
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: &basic-setup
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
  greeting:
    runs-on: ubuntu-latest
    steps:
      - *basic-setup
      - run: echo "deploying..."
      - uses: /samurodriguez/.github/actions/greeting@main
        with:
          name: Paco
      - uses: /samurodriguez/.github/actions/notify-slack@main
        id: notify-slack
        with:
          message: Holaaa
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          type: danger
      - run: echo ${{ steps.notify-slack.outputs.message-sent-at }}
